users:
  - name: john
    first: John
    middle: Winsher
    last: Goldy
    uid: 1051

  - name: martin
    first: Martin
    middle: Rodolfo
    last: Kpade
    uid: 1052

  - name: ramanou
    first: Ramanou
    middle: Bony
    last: Issaka
    uid: 1053


